import * as fs from "node:fs";
import * as path from "node:path";

const KNOWN_GLOBALS: Record<string, string> = {
  node: "Node information and control",
  wifi: "WiFi station and AP control",
  file: "File system operations",
  gpio: "GPIO pin control",
  adc: "Analog-to-digital conversion",
  tmr: "Software timers",
  pwm: "Pulse-width modulation",
  i2c: "I2C bus interface",
  spi: "SPI bus interface",
  uart: "UART serial interface",
  ow: "1-Wire interface",
  net: "Network (TCP/UDP/DNS)",
  mqtt: "MQTT client",
  http: "HTTP client/server",
  websocket: "WebSocket client",
  coap: "CoAP client",
  tls: "TLS/SSL",
  sjson: "Safe JSON",
  dht: "DHT temperature/humidity sensor",
  cron: "Cron-style scheduling",
  rtctime: "RTC time",
  rtcmem: "RTC memory",
  sntp: "Simple NTP",
  mDNS: "mDNS responder",
  ws2801: "WS2801 LED strip",
  ws2812: "WS2812 LED strip",
  apa102: "APA102 LED strip",
  bit: "Bit operations",
  struct: "Pack/unpack structures",
  enduser_setup: "Captive portal for WiFi setup",
  gdbstub: "GDB remote debugging",
};

function formatGlobal(name: string, doc: string): string[] {
  return [
    `--- ${doc}`,
    `---@type NodeMCUModule`,
    `${name} = ${name} or {}`,
    "",
  ];
}

export interface GenerateApiOptions {
  modules: string[];
  outputPath: string;
  projectName?: string;
}

export function generateLuaApiFile(opts: GenerateApiOptions): string {
  const lines: string[] = [];
  lines.push("---@meta");
  lines.push("--- Auto-generated by nodemcu-vscode. Do not edit by hand.");
  lines.push("---@diagnostic disable");
  lines.push("");

  lines.push("---@class NodeMCUModule");
  lines.push("");

  const sorted = Array.from(new Set(opts.modules.map((m) => m.toLowerCase()))).sort();
  for (const mod of sorted) {
    const doc = KNOWN_GLOBALS[mod] ?? `${mod} module`;
    lines.push(...formatGlobal(mod, doc));
  }

  fs.mkdirSync(path.dirname(opts.outputPath), { recursive: true });
  fs.writeFileSync(opts.outputPath, lines.join("\n"), "utf-8");
  return opts.outputPath;
}

export function generateLuaRc(opts: { workspaceRoot: string; luaModulesDirs: string[]; apiFile: string }): string {
  const cfg = {
    "$schema": "https://raw.githubusercontent.com/sumneko/lua-language-schema/master/schema.json",
    "runtime": {
      path: opts.luaModulesDirs.map((d) => d.replace(/\\/g, "/")).join(";"),
    },
    "workspace": {
      library: opts.luaModulesDirs.map((d) => d.replace(/\\/g, "/")).join(";"),
      checkThirdParty: false,
    },
    "diagnostics": {
      globals: ["node", "wifi", "file", "gpio", "adc", "tmr", "pwm", "i2c", "spi", "uart", "ow", "net", "mqtt", "http", "websocket", "coap", "tls", "sjson", "dht", "cron", "rtctime", "rtcmem", "sntp"],
    },
  };
  return JSON.stringify(cfg, null, 2) + "\n";
}

export function writeLuaRc(opts: { workspaceRoot: string; luaModulesDirs: string[]; apiFile: string }): string {
  const outPath = path.join(opts.workspaceRoot, ".luarc.json");
  fs.writeFileSync(outPath, generateLuaRc(opts), "utf-8");
  return outPath;
}
